[package]
name = "iterify"
version = "0.1.0"
edition = "2021"
description = "Turn any type into an iterator with closures!"
license-file = "LICENSE.md"
readme = "README.md"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
